services:
  hydra-node-alice:
    image: ghcr.io/cardano-scaling/hydra-node:1.0.0
    volumes:
      - .:/devnet
      - ./persistence/alice:/devnet/persistence/alice
    ports:
      - "4001:4001"
      - "5001:5001"
    command:
      [
        "--node-id", "1",
        "--api-host", "0.0.0.0",
        "--listen", "172.16.238.10:5001",
        "--monitoring-port", "6001",
        "--api-port", "4001",
        "--peer", "172.16.238.30:5003",
        "--hydra-signing-key", "/devnet/credentials/alice/alice-hydra.sk",
        "--hydra-verification-key", "/devnet/credentials/ida/ida-hydra.vk",
        "--persistence-dir", "/devnet/persistence/alice",
        "--offline-head-seed", "0000000000000000000000000000000000000000000000000000000000000001",
        "--ledger-protocol-parameters", "/devnet/protocol-parameters.json",
        "--initial-utxo", "/devnet/utxo-1.json"
      ]
    networks:
      hydra_net:
        ipv4_address: 172.16.238.10
    restart: always

  hydra-node-bob:
    image: ghcr.io/cardano-scaling/hydra-node:1.0.0
    volumes:
      - .:/devnet
      - ./persistence/bob:/devnet/persistence/bob
    ports:
      - "4002:4002"
      - "5002:5002"
    command:
      [
        "--node-id", "2",
        "--api-host", "0.0.0.0",
        "--listen", "172.16.238.20:5002",
        "--monitoring-port", "6002",
        "--api-port", "4002",
        "--peer", "172.16.238.40:5004",
        "--hydra-signing-key", "/devnet/credentials/bob/bob-hydra.sk",
        "--hydra-verification-key", "/devnet/credentials/ida/ida-hydra.vk",
        "--persistence-dir", "/devnet/persistence/bob",
        "--offline-head-seed", "0000000000000000000000000000000000000000000000000000000000000002",
        "--ledger-protocol-parameters", "/devnet/protocol-parameters.json",
        "--initial-utxo", "/devnet/utxo-2.json"
      ]
    networks:
      hydra_net:
        ipv4_address: 172.16.238.20
    restart: always

  hydra-node-ida-1:
      image: ghcr.io/cardano-scaling/hydra-node:1.0.0
      volumes:
        - .:/devnet
        - ./persistence/ida-1:/devnet/persistence/ida-1
      ports:
        - "4003:4003"
        - "5003:5003"
      command:
        [
          "--node-id", "3",
          "--api-host", "0.0.0.0",
          "--listen", "172.16.238.30:5003",
          "--monitoring-port", "6003",
          "--api-port", "4003",
          "--peer", "172.16.238.10:5001",
          "--hydra-signing-key", "/devnet/credentials/ida/ida-hydra.sk",
          "--hydra-verification-key", "/devnet/credentials/alice/alice-hydra.vk",
          "--persistence-dir", "/devnet/persistence/ida-1",
          "--offline-head-seed", "0000000000000000000000000000000000000000000000000000000000000001",
          "--ledger-protocol-parameters", "/devnet/protocol-parameters.json",
          "--initial-utxo", "/devnet/utxo-1.json"
        ]
      networks:
        hydra_net:
          ipv4_address: 172.16.238.30
      restart: always

  hydra-node-ida-2:
      image: ghcr.io/cardano-scaling/hydra-node:1.0.0
      volumes:
        - .:/devnet
        - ./persistence/ida-2:/devnet/persistence/ida-2
      ports:
        - "4004:4004"
        - "5004:5004"
      command:
        [
          "--node-id", "4",
          "--api-host", "0.0.0.0",
          "--listen", "172.16.238.40:5004",
          "--monitoring-port", "6004",
          "--peer", "172.16.238.20:5002",
         "--api-port", "4004",
          "--hydra-signing-key", "/devnet/credentials/ida/ida-hydra.sk",
          "--hydra-verification-key", "/devnet/credentials/bob/bob-hydra.vk",
          "--persistence-dir", "/devnet/persistence/ida-2",
          "--offline-head-seed", "0000000000000000000000000000000000000000000000000000000000000002",
          "--ledger-protocol-parameters", "/devnet/protocol-parameters.json",
          "--initial-utxo", "/devnet/utxo-2.json"
        ]
      networks:
        hydra_net:
          ipv4_address: 172.16.238.40
      restart: always

volumes:
  alice_persistence:
  bob_persistence:
  ida_1_persistence:
  ida_2_persistence:

networks:
  hydra_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
