services:
  hydra-node-1:
    image: ghcr.io/cardano-scaling/hydra-node:0.22.0
    volumes:
      - .:/devnet
      - ./persistence/alice:/devnet/persistence/alice
    ports:
      - "4001:4001"
      - "5001:5001"
    command:
      [
        "--node-id", "1",
        "--api-host", "0.0.0.0",
        "--listen", "172.16.238.10:5001",
        "--monitoring-port", "6001",
        "--peer", "172.16.238.20:5002",
        "--hydra-signing-key", "/devnet/credentials/alice-hydra.sk",
        "--hydra-verification-key", "/devnet/credentials/bob-hydra.vk",
        "--persistence-dir", "/devnet/persistence/alice",
        "--offline-head-seed", "0000000000000000000000000000000000000000000000000000000000000000",
        "--ledger-protocol-parameters", "/devnet/protocol-parameters.json",
        "--initial-utxo", "/devnet/utxo.json"
      ]
    networks:
      hydra_net:
        ipv4_address: 172.16.238.10
    restart: always

  hydra-node-2:
    image: ghcr.io/cardano-scaling/hydra-node:0.22.0
    volumes:
      - .:/devnet
      - ./persistence/bob:/devnet/persistence/bob
    ports:
      - "4002:4002"
      - "5002:5002"
    command:
      [
        "--node-id", "2",
        "--api-host", "0.0.0.0",
        "--listen", "172.16.238.20:5002",
        "--monitoring-port", "6002",
        "--api-port", "4002",
        "--peer", "172.16.238.10:5001",
        "--hydra-signing-key", "/devnet/credentials/bob-hydra.sk",
        "--hydra-verification-key", "/devnet/credentials/alice-hydra.vk",
        "--persistence-dir", "/devnet/persistence/bob",
        "--offline-head-seed", "0000000000000000000000000000000000000000000000000000000000000000",
        "--ledger-protocol-parameters", "/devnet/protocol-parameters.json",
        "--initial-utxo", "/devnet/utxo.json"
      ]
    networks:
      hydra_net:
        ipv4_address: 172.16.238.20
    restart: always

volumes:
  alice_persistence:
  bob_persistence:

networks:
  hydra_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
